### ISSUE TITLE
Links of "papers" are not available

### ISSUE THREAD

**Issue by solomonxie** [wadelau/Base62x#6]
Just found in the README that these links are not available anymore:
```
[ -R/p2SK ](http://ufqi.com/naturedns/search?q=-r/C2TZ) , page url in [ -URL4P ](http://ufqi.com/naturedns/search?q=-url4p) .

[-Base62x in RearchGate, -R/12Sb ](http://ufqi.com/naturedns/search?q=-R/12Sb ) .
```

You might want to reference these to stable links instead of searching result.

**Comment by wadelau** [comment]
Thanks for this notice. The URL4P links have been updated.
