### ISSUE TITLE
Base62x::decode如果缺少字符等会操成死循环 超时504

### ISSUE THREAD

**Issue by hahaapi** [wadelau/Base62x#7]
中文测试 转换出来的是vBYjvfQ7vhMBwAx2L
去掉末尾一个两个三个字符只是末尾输出一个乱字符

如果去掉后面4个字符
如
echo Base62x::decode('vBYjvfQ7vhMBw');

死循坏了

**Comment by wadelau** [comment]
谢谢反馈，确实存在测试时未发现bug，已修复，已commit修正版本。
+test4IssueFromHahaapi.php 供参考.

**Comment by wadelau** [comment]
@hahaapi ，have you had run another test for this issue on the updated codes?
Please feedback whether it had been fixed or not.

**Comment by hahaapi** [comment]
测试OK了，感谢你
